# Generated by Django 2.1.8 on 2020-07-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200714_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='文章的作者'),
        ),
    ]
