# Generated by Django 2.1.8 on 2020-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200714_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='view_counter',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
