# Generated by Django 2.1.8 on 2020-07-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200714_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telphone',
        ),
    ]
